"""Correctness tests for the ARK-ASR-3B megakernel pipeline vs golden reference.

These tests load the model once (session-scoped), prewarm the CUDA graphs, and
assert the megakernel transcript is byte-identical to the stock eager
``model.generate`` greedy reference captured in ``golden/ark_reference.json``.

The golden file is gitignored (generated by ``scripts/make_ark_golden.py``); the
tests ``pytest.skip`` if it is absent so the suite runs green on a fresh clone
without the 3B model downloaded.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest
import soundfile as sf

REPO_ROOT = Path(__file__).resolve().parents[1]
GOLDEN_PATH = REPO_ROOT / "golden" / "ark_reference.json"
# Fixtures live in the main starling checkout (the worktree shares the index but
# not the working-tree untracked files like tests/fixtures).
MAIN_REPO = Path("/home/m0hawk/Documents/starling")
FIXTURES = MAIN_REPO / "tests" / "fixtures"
if not FIXTURES.exists():
    FIXTURES = REPO_ROOT.parent / "tests" / "fixtures"
if not FIXTURES.exists():
    FIXTURES = REPO_ROOT / "tests" / "fixtures"


def _load_golden():
    if not GOLDEN_PATH.exists():
        pytest.skip(f"golden reference {GOLDEN_PATH} not found; run scripts/make_ark_golden.py")
    with open(GOLDEN_PATH) as f:
        return json.load(f)


@pytest.fixture(scope="module")
def pipeline():
    """Build and prewarm the MegaPipeline once for the whole module."""
    from starling.ark.pipeline import MegaPipeline

    pipe = MegaPipeline.from_pretrained(steps_per_replay=16, max_cache_len=4096)
    pipe.prewarm()
    return pipe


@pytest.fixture(scope="module")
def golden():
    return _load_golden()


def _wav(name: str) -> np.ndarray:
    path = FIXTURES / f"{name}.wav"
    if not path.exists():
        pytest.skip(f"fixture {path} not found")
    wav, sr = sf.read(str(path))
    if wav.ndim > 1:
        wav = wav[:, 0]
    return np.ascontiguousarray(wav, dtype=np.float32)


@pytest.mark.parametrize("fixture", ["short", "medium", "long"])
def test_transcribe_byte_identical_to_golden(pipeline, golden, fixture):
    """The megakernel transcript tokens must match the golden greedy reference."""
    if fixture not in golden:
        pytest.skip(f"golden has no entry for {fixture!r}")
    wav = _wav(fixture)
    text, ids = pipeline.transcribe(wav, max_new_tokens=200)
    ids = ids[0].tolist()
    golden_ids = golden[fixture]["ids"]
    assert ids == golden_ids, (
        f"{fixture}: megakernel token sequence diverges from golden reference; "
        f"got {len(ids)} tokens, golden has {len(golden_ids)}. "
        f"first divergence at index "
        f"{next((i for i,(a,b) in enumerate(zip(ids,golden_ids)) if a!=b), None)}"
    )
    # transcript text must also match (decoded from the same token ids)
    golden_text = golden[fixture]["text"]
    assert text.strip() == golden_text.strip(), f"{fixture}: transcript text mismatch"
