"""Correctness tests for the ARK-ASR-0.6B megakernel pipeline vs golden reference.

These tests load the model once (session-scoped), prewarm the CUDA graphs, and
assert the megakernel transcript is byte-identical to the stock eager
``model.generate`` greedy reference captured in ``golden/ark06_reference.json``.

The golden file is gitignored (generated by ``scripts/make_ark06_golden.py``);
the tests ``pytest.skip`` if it is absent so the suite runs green on a fresh
clone without the 0.6B model downloaded.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest
import soundfile as sf

torch = pytest.importorskip("torch")

needs_cuda = pytest.mark.skipif(
    not torch.cuda.is_available(),
    reason="CUDA required for ARK-ASR-0.6B megakernel tests",
)

REPO_ROOT = Path(__file__).resolve().parents[1]
GOLDEN_PATH = REPO_ROOT / "golden" / "ark06_reference.json"
# Fixtures live in the main starling checkout (the worktree shares the index but
# not the working-tree untracked files like tests/fixtures).
MAIN_REPO = Path("/home/m0hawk/Documents/starling")
FIXTURES = MAIN_REPO / "tests" / "fixtures"
if not FIXTURES.exists():
    FIXTURES = REPO_ROOT.parent / "tests" / "fixtures"
if not FIXTURES.exists():
    FIXTURES = REPO_ROOT / "tests" / "fixtures"


def _load_golden():
    if not GOLDEN_PATH.exists():
        pytest.skip(f"golden reference {GOLDEN_PATH} not found; run scripts/make_ark06_golden.py")
    with open(GOLDEN_PATH) as f:
        return json.load(f)


@pytest.fixture(scope="module")
def pipeline():
    """Build and prewarm the MegaPipeline once for the whole module."""
    from starling.ark06.pipeline import MegaPipeline

    pipe = MegaPipeline.from_pretrained(steps_per_replay=16, max_cache_len=4096)
    pipe.prewarm()
    return pipe


@pytest.fixture(scope="module")
def golden():
    return _load_golden()


def _wav(name: str) -> np.ndarray:
    path = FIXTURES / f"{name}.wav"
    if not path.exists():
        pytest.skip(f"fixture {path} not found")
    wav, sr = sf.read(str(path))
    if wav.ndim > 1:
        wav = wav[:, 0]
    return np.ascontiguousarray(wav, dtype=np.float32)


@needs_cuda
@pytest.mark.parametrize("fixture", ["short", "medium", "long"])
def test_transcribe_byte_identical_to_golden(pipeline, golden, fixture):
    """The megakernel transcript tokens must match the golden greedy reference."""
    if fixture not in golden:
        pytest.skip(f"golden has no entry for {fixture!r}")
    wav = _wav(fixture)
    text, ids = pipeline.transcribe(wav, max_new_tokens=200)
    ids = ids[0].tolist()
    golden_ids = golden[fixture]["ids"]
    assert ids == golden_ids, (
        f"{fixture}: megakernel token sequence diverges from golden reference; "
        f"got {len(ids)} tokens, golden has {len(golden_ids)}. "
        f"first divergence at index "
        f"{next((i for i,(a,b) in enumerate(zip(ids,golden_ids)) if a!=b), None)}"
    )
    # transcript text must also match (decoded from the same token ids)
    golden_text = golden[fixture]["text"]
    assert text.strip() == golden_text.strip(), f"{fixture}: transcript text mismatch"


def test_bucket_mel_pads_to_grid_and_caps():
    """`_bucket_mel` rounds mel_T up to the bucket grid, caps at 3000, no-ops
    when already aligned/disabled. Pure tensor logic -- no model load."""
    import torch

    from starling.ark06.pipeline import MegaPipeline

    p = MegaPipeline.__new__(MegaPipeline)  # bypass __init__ (no model needed)
    p.shape_bucketing = True
    p.mel_bucket_frames = 512

    mel = torch.zeros(1, 128, 700)
    out = p._bucket_mel(mel)
    assert out.shape[2] == 1024, "700 should pad up to the next 512-multiple (1024)"
    assert torch.equal(out[:, :, :700], mel), "valid region must be preserved"
    assert out[:, :, 700:].abs().sum().item() == 0.0, "padding must be zeros"

    # capped at 3000 (2 * ENCODER_MAX_SOURCE_POSITIONS): 2900 -> 3072 -> 3000
    assert p._bucket_mel(torch.zeros(1, 128, 2900)).shape[2] == 3000

    # already on the grid -> returned unchanged (no copy)
    on_grid = torch.zeros(1, 128, 1024)
    assert p._bucket_mel(on_grid) is on_grid

    # disabled -> unchanged
    p.shape_bucketing = False
    assert p._bucket_mel(mel) is mel


@needs_cuda
@pytest.mark.parametrize("fixture", ["short", "medium", "long"])
def test_bucketing_is_text_byte_exact(pipeline, fixture):
    """Shape-bucketing must not change the decoded transcript.

    Bucketing pads the mel with trailing silence (which the Whisper encoder is
    trained on) and truncates the extra adapter features, so the emitted text is
    identical to the strict per-shape (unbucketed) path -- the pipeline's
    correctness gate, mirroring the parakeet bucketing standard.
    """
    wav = _wav(fixture)
    prev = pipeline.shape_bucketing
    try:
        pipeline.shape_bucketing = False
        ref_text, _ = pipeline.transcribe(wav, max_new_tokens=200)
        pipeline.shape_bucketing = True
        buck_text, _ = pipeline.transcribe(wav, max_new_tokens=200)
    finally:
        pipeline.shape_bucketing = prev
    assert buck_text.strip() == ref_text.strip(), (
        f"{fixture}: bucketed transcript differs from the unbucketed reference"
    )


# --------------------------------------------------------------------------- #
# CPU-safe suppression-recipe tests (no model, no CUDA)
# --------------------------------------------------------------------------- #
class _MockTokenizer:
    """Tiny stand-in exposing the tokenizer surface build_bad_token_ids needs."""

    def __init__(self) -> None:
        self.eos_token_id = 151645
        self.vocab_size = 163958
        self.all_special_ids = [151643, 151645, 151665, 151666, 151667, 151668, 151669]
        self._added = {
            "<|bicodec_0|>": 151700,
            "<|bicodec_1|>": 151701,
            "<regular>": 400,  # starts with "<" but not a bicodec/special token
            "plain": 500,
        }

    def get_added_vocab(self):
        return dict(self._added)


def test_build_bad_token_ids_card_recipe_cpu():
    """The recipe bans chat specials + `<...>` added vocab, minus EOS."""
    from starling.ark06.config import EOS_TOKEN_ID, build_bad_token_ids

    bad = build_bad_token_ids(_MockTokenizer())
    # all chat specials except EOS are banned...
    assert 151643 in bad and 151665 in bad and 151669 in bad
    # ...the <...> added-vocab tokens are banned (incl. the non-bicodec one:
    # the card recipe bans by "<...>" shape, not by prefix)...
    assert 151700 in bad and 151701 in bad and 400 in bad
    # ...plain added vocab is kept, and EOS must stay emittable.
    assert 500 not in bad
    assert EOS_TOKEN_ID not in bad and 151645 not in bad


def test_build_bad_token_ids_clamps_vocab_drift_cpu():
    """Stale ids outside vocab_size are dropped (un-emittable anyway)."""
    from starling.ark06.config import build_bad_token_ids

    tok = _MockTokenizer()
    tok.all_special_ids = list(tok.all_special_ids) + [999_999]
    assert 999_999 not in build_bad_token_ids(tok)


def test_bad_penalty_builder_none_path_adds_no_tensors_cpu():
    """The shared 3B decode path (bad_token_ids=None) allocates nothing."""
    from starling.ark.llm_mega import LLMMega

    assert LLMMega._build_bad_penalty(None, 163958, torch.float32, "cpu") is None
    assert LLMMega._build_bad_penalty(set(), 163958, torch.float32, "cpu") is None
    pen = LLMMega._build_bad_penalty(
        frozenset({1, 5, 999_999}), 163958, torch.float32, "cpu"
    )
    assert pen is not None and pen.shape == (1, 1, 163958)
    assert pen[0, 0, 1] == torch.finfo(torch.float32).min
    assert pen[0, 0, 5] == torch.finfo(torch.float32).min
    assert pen[0, 0, 0] == 0.0  # unbanned rows stay zero
